version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead

  web:
    build: .
    ports:
      - 8000:80
    volumes:
      - ".:/var/www/html"


